const { toWei } = web3.utils;

// ERROR CODES
const ERR_ZERO = "ERR_ZERO";
const ERR_BAL_ETH = "ERR_BAL_ETH";
const ERR_NOT_OWNER = "ERR_NOT_OWNER";
const ERR_BAL_PRIME = "ERR_BAL_PRIME";
const ERR_BAL_STRIKE = "ERR_BAL_STRIKE";
const ERR_BAL_REDEEM = "ERR_BAL_REDEEM";
const ERR_BAL_TOKENS = "ERR_BAL_TOKENS";
const ERR_BAL_OPTIONS = "ERR_BAL_OPTIONS";
const ERR_OPTION_TYPE = "ERR_OPTION_TYPE";
const ERR_PAUSED = "Pausable: paused";

// COMMON AMOUNTS
const ROUNDING_ERR = 10 ** 8;
const HUNDRETH = toWei("0.01");
const ONE_ETHER = toWei("1");
const TWO_ETHER = toWei("2");
const FIVE_ETHER = toWei("5");
const TEN_ETHER = toWei("10");
const FIFTY_ETHER = toWei("50");
const HUNDRED_ETHER = toWei("100");
const THOUSAND_ETHER = toWei("1000");
const MILLION_ETHER = toWei("1000000");
const MIN_LIQUIDITY = 10 ** 4;
const ACCURACY = 10 ** 12;
const MAX_SLIPPAGE = 5;

// CORE ADDRESSES
const TREASURER = "0x9eb7f2591ed42dee9315b6e2aaf21ba85ea69f8c";
const MAINNET_DAI = "0x6b175474e89094c44da98b954eedeac495271d0f";
const MAINNET_ORACLE = "0xdA17fbEdA95222f331Cb1D252401F4b44F49f7A0";
const MAINNET_COMPOUND_ETH = "0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5";
const MAINNET_WETH = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2";
const MAINNET_UNI_FACTORY = "0xc0a47dFe034B400B47bDaD5FecDa2621de6c4d95";

module.exports = {
    ERR_ZERO,
    ERR_BAL_ETH,
    ERR_NOT_OWNER,
    ERR_BAL_PRIME,
    ERR_BAL_ETH,
    ERR_BAL_STRIKE,
    ERR_BAL_REDEEM,
    ERR_BAL_TOKENS,
    ERR_BAL_OPTIONS,
    ERR_OPTION_TYPE,
    ROUNDING_ERR,
    HUNDRETH,
    ONE_ETHER,
    TWO_ETHER,
    FIVE_ETHER,
    TEN_ETHER,
    FIFTY_ETHER,
    HUNDRED_ETHER,
    THOUSAND_ETHER,
    MILLION_ETHER,
    MIN_LIQUIDITY,
    ACCURACY,
    TREASURER,
    MAINNET_DAI,
    MAINNET_ORACLE,
    MAINNET_COMPOUND_ETH,
    MAINNET_WETH,
    MAINNET_UNI_FACTORY,
    MAX_SLIPPAGE,
};
