const INITIAL_CONTEXT = {
    items: {
        'N/A' : {id: 'N/A', content: 'N/A', payload: 'N/A'},
        'asset-dai': {id: 'asset-dai', content: 'DAI', type: 'asset', index: 'start', payload: 'DAI'},
        'expiration-2': {id: 'expiration-2', content: '1609459200', type: 'expiration', index: 'start', payload: '1609459200',},
        'address-3': {id: 'address-3', content: 'address 3', type: 'address', index: 'start', payload: 'carbonprotocol.eth',},
        'asset-mkr': {id: 'asset-mkr', content: 'MKR', type: 'asset', index: 'start', payload: 'MKR',},
        'asset-snx': {id: 'asset-snx', content: 'SNX', type: 'asset', index: 'start', payload: 'SNX'},
        'asset-u': {
            id: 'asset-u', 
            content: 'U', 
            type: 'asset', 
            index: 'start',
            iconName: 'u.png',
            mainnet: '',
            rinkeby: '',
            payload: 'U',
        },
        'asset-s': {
            id: 'asset-s', 
            content: 'S', 
            type: 'asset', 
            index: 'start',
            iconName: 's.png',
            mainnet: '',
            rinkeby: '',
            payload: 'S',
        },
        'asset-tUSD': {
            id: 'asset-tUSD', 
            content: 'tUSD', 
            type: 'asset', 
            index: 'start',
            iconName: 's.png',
            mainnet: '',
            rinkeby: '',
            payload: 'tUSD',
        },
        'asset-tETH': {
            id: 'asset-tETH', 
            content: 'tETH', 
            type: 'asset', 
            index: 'start',
            iconName: 's.png',
            mainnet: '',
            rinkeby: '',
            payload: 'tETH',
        },
        'expiration-may': {
            id: 'expiration-may', 
            content: 'May 15, 2020, 11:59pm UTC', 
            type: 'expiration', 
            payload: '1589587185',
        },
        'expiration-june': {
            id: 'expiration-june', 
            content: 'June 19, 2020, 11:59pm UTC', 
            type: 'expiration', 
            payload: '1592611185',
        },
        'expiration-september': {
            id: 'expiration-september', 
            content: 'September 18, 2020, 11:59pm UTC', 
            type: 'expiration', 
            payload: '1600473585',
        },
        'expiration-december': {
            id: 'expiration-december', 
            content: 'December 18, 2020, 11:59pm UTC', 
            type: 'expiration', 
            payload: '1608335985',
        },
    },
    assets: {
        'assetIds' : ['asset-dai', 'asset-tUSD', 'asset-tETH',],
        'asset-snx': {
                        id: 'asset-snx', 
                        content: 'SNX', 
                        type: 'asset', 
                        index: 'start',
                        iconName: 'snx.png',
                        mainnet: '',
                        rinkeby: '',
                        payload: 'SNX',
                    },
        'asset-dai': {
                        id: 'asset-dai', 
                        content: 'DAI', 
                        type: 'asset', 
                        index: 'start',
                        iconName: 'dai.png',
                        mainnet: '',
                        rinkeby: '',
                        payload: 'DAI',
                    },
        'asset-mkr': {
                        id: 'asset-mkr', 
                        content: 'MKR', 
                        type: 'asset', 
                        index: 'start',
                        iconName: 'mkr.png',
                        mainnet: '',
                        rinkeby: '',
                        payload: 'MKR',
                    },
        'asset-u': {
                        id: 'asset-u', 
                        content: 'U', 
                        type: 'asset', 
                        index: 'start',
                        iconName: 'u.png',
                        mainnet: '',
                        rinkeby: '',
                        payload: 'U',
                    },
        'asset-s': {
                        id: 'asset-s', 
                        content: 'S', 
                        type: 'asset', 
                        index: 'start',
                        iconName: 's.png',
                        mainnet: '',
                        rinkeby: '',
                        payload: 'S',
                    },
        'asset-tUSD': {
                        id: 'asset-tUSD', 
                        content: 'tUSD', 
                        type: 'asset', 
                        index: 'start',
                        iconName: 's.png',
                        mainnet: '',
                        rinkeby: '',
                        payload: 'tUSD',
                    },
        'asset-tETH': {
                        id: 'asset-tETH', 
                        content: 'tETH', 
                        type: 'asset', 
                        index: 'start',
                        iconName: 's.png',
                        mainnet: '',
                        rinkeby: '',
                        payload: 'tETH',
                    },
                    
    },
    expirations: {
        /* 'expirationIds': ['expiration-2'],
        'expiration-2': {id: 'expiration-2', content: '1609459200', type: 'expiration', index: 'start', payload: '1609459200',}, */
        'expirationIds': ['expiration-may', 'expiration-june', 'expiration-september', 'expiration-december',],
        'expiration-may': {
            id: 'expiration-may', 
            content: 'May 15, 2020, 11:59pm UTC', 
            type: 'expiration', 
            payload: '1589587185',
        },
        'expiration-june': {
            id: 'expiration-june', 
            content: 'June 19, 2020, 11:59pm UTC', 
            type: 'expiration', 
            payload: '1592611185',
        },
        'expiration-september': {
            id: 'expiration-september', 
            content: 'September 18, 2020, 11:59pm UTC', 
            type: 'expiration', 
            payload: '1600473585',
        },
        'expiration-december': {
            id: 'expiration-december', 
            content: 'December 18, 2020, 11:59pm UTC', 
            type: 'expiration', 
            payload: '1608335985',
        },
    },
    addresses: {
        'addressIds': ['address-3'],
        'address-3': {id: 'address-3', content: 'address 3', type: 'address', index: 'start',},
    },
    columns: {
        'start': {
            id: 'start',
            title: 'Parts',
            itemIds: [
                        'asset-dai',  
                        'asset-tUSD', 
                        'asset-tETH',
                        'expiration-june',
                    ],
            board: false,
        },
        'asset': {
            id: 'asset',
            title: 'Assets',
            itemIds: ['asset-dai', 'asset-tUSD', 'asset-tETH',],
            board: false,
        },
        'board': {
            id: 'board',
            title: 'Board',
            itemIds: [],
            board: true,
        },
        'expiration': {
            id: 'expiration',
            title: 'Expiration Dates',
            itemIds: ['expiration-2',],
            board: false,
        },
        'address': {
            id: 'address',
            title: 'Addresses',
            itemIds: ['address-3'],
            board: false,
        },
        'collateralBoard': {
            id: 'collateralBoard',
            title: 'Collateral',
            itemIds: [],
            board: true,
        },
        'paymentBoard': {
            id: 'paymentBoard',
            title: 'Payment',
            itemIds: [],
            board: true,
        },
        'expirationBoard': {
            id: 'expirationBoard',
            title: 'Expires',
            itemIds: [],
            board: true,
        },
        'addressBoard': {
            id: 'addressBoard',
            title: 'Payment Receiver',
            itemIds: [],
            board: true,
        },


        '5': {
            id: '5',
            title: 'Evolution',
            itemIds: [],
            board: true,
        },
        '6': {
            id: '6',
            title: 'Double Collateral',
            itemIds: [],
            board: true,
        },
        '7': {
            id: '7',
            title: 'Double Payment',
            itemIds: [],
            board: true,
        },
        '8': {
            id: '8',
            title: 'NFT',
            itemIds: [],
            board: true,
        },
        '9': {
            id: '9',
            title: 'Interest Receiver',
            itemIds: [],
            board: true,
        },
    },
    columnOrder: [
        'start', 
        'collateralBoard', 'paymentBoard', 'expirationBoard', 
        'addressBoard', '5', '6', 
        '7', '8', '9',
    ],
};

export default INITIAL_CONTEXT;